version: "3.9"
services:
  integrator_service:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:80"
    command: uvicorn app.main:app --host 0.0.0.0 --port 80