version: "3.9"
services:
  integrator_service:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:80"
    volumes:
      - "./databases/TestService.sample:/code/databases/localService.sqlite"
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
  external_service:
    build:
      context: ../ExternalService/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:80"
